### ISSUE TITLE
Specify which sidekiq-cron version is available

### ISSUE THREAD

**Issue by ozachun** [floraison/fugit#102]
## Issue description
Stated in https://github.com/floraison/fugit?tab=readme-ov-file 「Related projects - Similar, sometimes overlapping projects」of [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) - recent versions of Sidekiq-Cron use fugit to parse cron strings

In the above description, it says that it is available in the recent versions of Sidekiq-Corn, but from which version is it available? Not stated.

## How to reproduce
version
Booted Rails 7.0.7, Running in ruby 3.2.2, Sidekiq Pro 5.5.8 / Sidekiq Enterprise 2.5.3

The simplest piece of code that reproduces the issue, for example:

cron.register('07 3,11,15 * * *', 'CreateDfplusCsvWorker', 'args' => [])
```ruby
config.periodic do |cron|
  cron.register('0 5 * * mon#1', SampleWorker', 'args' => [])
end
```

bundle exec rails c
```
>  SampleWorker.perform_async()
```

## Expected behaviour
It should be stated from which sidekiq-corn version it is available.

**Comment by jmettraux** [comment]
In [Sidekiq-Cron's CHANGELOG.md](https://github.com/sidekiq-cron/sidekiq-cron/blob/master/CHANGELOG.md#100), it is specified that it uses fugit since version 1.0.0. According to the [list of Sidekiq-Cron versions](https://rubygems.org/gems/sidekiq-cron/versions), version 1.0.0 is available since 2018-07-09.

**Comment by jmettraux** [comment]
I consider your issue fixed. I stated in the [README.md](https://github.com/floraison/fugit/blob/ee4712ee0b66c52547a411d686936cc477763376/README.md#projects-using-fugit) what version of Sidekiq-Cron started using fugit directly instead of rufus-scheduler. You said "not stated" as the issue, it is now *stated*. Issue closed.

Feel free to open a new issue if you spot anything else.

Please understand that I do not own a license of Sidekiq-pro, so I cannot test it for you.

Please also understand that I am developing this library on my spare time mostly, I cannot give you support for free for libraries that I did not develop. If you can prove that you have an issue with fugit, and you can describe it so that I can reproduce it, I will do my best to fix it.

Best regards.

**Comment by jmettraux** [comment]
And

```ruby
config.periodic do |cron|
  cron.register('0 5 * * mon#1', SampleWorker', 'args' => [])
end
```
is not valid Ruby code, it should be
```ruby
config.periodic do |cron|
  cron.register('0 5 * * mon#1', 'SampleWorker', 'args' => [])
end
```
or
```ruby
config.periodic do |cron|
  cron.register('0 5 * * mon#1', SampleWorker, 'args' => [])
end
```

**Comment by ozachun** [comment]
Thank you for your response to the correction.
The issue has been resolved. Thank you!
